### ISSUE TITLE
Can this be translated?

### ISSUE THREAD

**Issue by dinism** [wjunkin/moodle-quiz_liveviewgrid#10]
File quizgraphics.php:
Something is wrong with answer id $qansid

File graph.php
$line->parameter['y_label_left'] = 'Number of Responses';

Is it compatible with 3.6?

**Comment by wjunkin** [comment]
Hi, Dinism,
Thanks for calling this to my attention. I have now moved the string "Number of Responses" to the language file so that it can be translated. The new version v 1.1.1 has been posted on Moodle.
If you find a problem please let me know. Additional comments and suggestions are always welcome.
This plugin works with Moodle 3.6.2 as well as earlier versions of Moodle (back to 3.2). Thanks for your interest in this plugin.

**Comment by dinism** [comment]
In file **quizgraphics.php**, are this messages to the user?
**line 37**: echo "\n<br />You must be authorized to access this site";
**line 44**: echo "\n<br />You must submit a valid questionid";
**line 135**: echo "\n<br />Something is wrong with answer id $qansid";

If yes, can this be translated too?
THANKS A LOT

**Comment by wjunkin** [comment]
Hi, Dinism,
Thanks for calling these to my attention. I have created language strings for each of these so I am closing this issue. Please let me know if you have any other suggestions.
