### ISSUE TITLE
Is this a "my error"?

### ISSUE THREAD

**Issue by dinism** [wjunkin/moodle-quiz_liveviewgrid#11]
![imagem](https://user-images.githubusercontent.com/14828021/54568299-939ad800-49ce-11e9-8060-3b2cf3b2d4dd.png)

My site is in PT but i get First Name and Last Name in english. The strings are in AMOS.
Is this a "my error"?

**Comment by wjunkin** [comment]
No, dinism,
This is my error. Thanks for letting me know about this error. I hope to fix this and also have a couple of new features in some new code that I will publish before the end of this week. Again, thanks.

**Comment by wjunkin** [comment]
Hi, Dinism,
I have corrected the error. The code now uses the strings from the language file. (I also updated the version so that your Moodle site will clear cache for the strings in this version.) The corrected version is now available at https://github.com/wjunkin/moodle-quiz_liveviewgrid 
I plan to post a new version on the official Moodle site very soon. The new version will have this corrected and include a few other changes. In the meantime, I hope that this will let you use program without the bug that you found. Thanks for catching this.
