### ISSUE TITLE
Missing strings. Hardcoded

### ISSUE THREAD

**Issue by dinism** [wjunkin/moodle-quiz_liveviewgrid#14]
![imagem](https://user-images.githubusercontent.com/14828021/57216651-5b843e80-6fe8-11e9-83a8-6246d15a9741.png)
**In portuguese (PT-PT)**

![imagem](https://user-images.githubusercontent.com/14828021/57216673-7060d200-6fe8-11e9-88fe-577419aa0c5a.png)

**report.php, line 223**
 if ($showanswer) {
                    $buttontext = "Hide correct answer";
                    $info = "Click to hide correct answer";
                } else {
                    $info = "Click to show correct answer";
                    $buttontext = "Show correct answer";
                }
                $togglekey = 'showanswer';
                echo liveview_button($buttontext, $hidden, $togglekey, $info)

**I think it must be**
if ($showanswer) {
                    $buttontext = get_string('clickhiderightanswer', 'quiz_liveviewgrid');
                    $info = get_string('hiderightanswer', 'quiz_liveviewgrid');
                } else {
                    $info = get_string('clickshowrightanswer', 'quiz_liveviewgrid');
                    $buttontext = get_string('showrightanswer', 'quiz_liveviewgrid');
                }
                $togglekey = 'showanswer';
                echo liveview_button($buttontext, $hidden, $togglekey, $info)

**Missing in lang file - quiz_liveviewgrid.php**

$string['clickshowrightanswer'] = 'Click to show correct answer';
$string['clickhiderightanswer'] = 'Click to hide correct answer';

$string['showrightanswer'] = 'Show correct answer';
$string['hiderightanswer'] = 'Hide correct answer';

**Comment by wjunkin** [comment]
Thanks for catching all the places where I did not have language strings. I think the version that is now installed at https://www.lakeviewpresbyterianchurch.org/Moodle_34 has all the language strings. However, if you see any that are missing, please let me know. Thanks for your help.
I think I have solved the problem that occurs with truncation. Previously my program truncated after the 4th character. I think I have changed this so that the program truncates after the 4th symbol. I think it will thus handle characters with accents, tildas, etc., properly. However, if you find any place where it truncates incorrectly, please let me know. 
Another group has requested that the tooltip for the question name include the question text as well. I think I have also done this.
Again, thanks for your help. I will be publishing this newer version to this Github very soon.
