### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by dinism** [wjunkin/moodle-quiz_liveviewgrid#16]
Take a look [this video](https://www.escolaagricolavendasnovas.com/images/error.mp4).
Ehy this image **not histogram**?
Testing last version 1.2.9, last commit afb53d2 
![imagem](https://user-images.githubusercontent.com/14828021/58630413-39c06380-82d7-11e9-974c-14c95134d8c8.png)

**Comment by wjunkin** [comment]
Hi, Dinism,
Your video was VERY helpful. I think the new version I have posted (I had to change one line in the tooltip_histogram.php file) has taken care of this problem. I was using the wrong id in one function, but because of the way that the quizzes were numbered on my site, on my site both the wrong and the correct id gave valid results. Because of your help I was able to take care of the bug. THANK YOU SO MUCH. YOU ARE A GREAT FRIEND.
