### ISSUE TITLE
Folder preview not supported

### ISSUE THREAD

**Issue by stylkand** [wjunkin/moodle-quiz_liveviewgrid#26]
Hello,
I noticed on the updated mobile app (Version 4.0) that it's not possible to preview a folder's files.
As shown in the following course, I press the "Documents" folder but nothing appears.

<img src="https://user-images.githubusercontent.com/75040336/166156381-40d1e25d-75a1-4466-b920-6ab546865af1.jpg" width="350">
In prior versions it was possible.

Happy May Day!

** I also changed the folder's "Display" settings(inline) as an admin but nothing changed.

UPDATE: Sorry, I accidentally posted an unaffiliated issue in this repo. Please ignore.

**Comment by wjunkin** [comment]
Thanks for alerting me to this problem. Since I have only been checking things out using a laptop computer, I was not aware of this problem. I will try to check this out very soon (Monday or soon after).
I assume that you are using the latest version of Live Report (v3.1 (2022042800)) and are running Moodle 4.0.

**Comment by wjunkin** [comment]
Since it looks like this issue is not connected directly to the Live Report plugin, I am going to close this issue. If this is not the case, please let me know and I will re-open this issue.
