### ISSUE TITLE
graphicshash.php should probably use get_record instead of get_records.

### ISSUE THREAD

**Issue by danmarsden** [wjunkin/moodle-quiz_liveviewgrid#4]
$quiztime = $DB->get_records_sql("
    SELECT max(qa.timemodified)
    FROM {question_attempts} qa
    JOIN {question_usages} qu ON qu.id = qa.questionusageid
    WHERE qu.contextid = ?", array($quizcontextid));

Should really be 
$quiztime = $DB->get_record_sql("
    SELECT max(qa.timemodified)
    FROM {question_attempts} qa
    JOIN {question_usages} qu ON qu.id = qa.questionusageid
    WHERE qu.contextid = ?", array($quizcontextid));

**Comment by wjunkin** [comment]
Hi, Dan,
I have changed the database call to get_record as you suggested. I wrote the original script as get_records because I was afraid that two students might answer questions at a time that was close enough so that the maximum value of the timemodified might be the same in two or more records. I feared that if the max method in the sql statement foudn more than one record, this might throw an error into the execution of the code. However, if this can't happen or if this does not cause an error when the code runs, then get_record will definitely be the better database call. So, I have changed it in the record.php script.
